name: 'Terraform GitHub Actions'

on: [push]

jobs:
  plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: .
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_comment: true
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
