name: 'Terraform GitHub Actions'

on: [push]

jobs:
  validate:
    name: 'Validate'
    runs-on: ubuntu-latest
    steps:
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: .
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_working_dir: .
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          TF_VAR_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
